// ---------------------------------------------------------------------------
// Emotion catalog — one-shot /char/motion-2 clips for the sidebar tester and
// on-screen emotion dock. Auto-generated from public/char/motion-2/fbx;
// regenerate whenever assets are added/renamed.
// ---------------------------------------------------------------------------
import type { EmotionDef } from "../../b3/b3-runtime/src/components/stores/navRigStore";

export interface EmotionGroup {
  /** Folder name under /char/motion-2/fbx (also part of each clip id). */
  folder: string;
  /** Human tab/section title. */
  title: string;
  items: EmotionDef[];
}

/** Shared ~0.14s "get up from the floor" preamble in these clips — skipped so
 *  one-shots begin standing (measured for the gesture set; extend as needed). */
const humanize = (s: string) =>
  s.replace(/\.fbx$/, "").replace(/-/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());

const make = (folder: string, name: string, startAt = 0): EmotionDef => ({
  id: `${folder}/${name}`,
  name,
  url: `/char/motion-2/fbx/${folder}/${name}.fbx`,
  label: humanize(name),
  ...(startAt > 0 ? { startAt } : {}),
});

export const EMOTION_GROUPS: EmotionGroup[] = [
  { folder: "pro-magic", title: "Pro magic", items: [
    make("pro-magic", "crouch-idle", 0),
    make("pro-magic", "crouch-to-standing-idle", 0),
    make("pro-magic", "crouch-turn-left-90", 0),
    make("pro-magic", "crouch-turn-right-90", 0),
    make("pro-magic", "crouch-walk-back", 0),
    make("pro-magic", "crouch-walk-forward", 0),
    make("pro-magic", "crouch-walk-left", 0),
    make("pro-magic", "crouch-walk-right", 0),
    make("pro-magic", "standing-1h-cast-spell-01", 0),
    make("pro-magic", "standing-1h-magic-attack-01", 0),
    make("pro-magic", "standing-1h-magic-attack-02", 0),
    make("pro-magic", "standing-1h-magic-attack-03", 0),
    make("pro-magic", "standing-2h-cast-spell-01", 0),
    make("pro-magic", "standing-2h-magic-area-attack-01", 0),
    make("pro-magic", "standing-2h-magic-area-attack-02", 0),
    make("pro-magic", "standing-2h-magic-attack-01", 0),
    make("pro-magic", "standing-2h-magic-attack-02", 0),
    make("pro-magic", "standing-2h-magic-attack-03", 0),
    make("pro-magic", "standing-2h-magic-attack-04", 0),
    make("pro-magic", "standing-2h-magic-attack-05", 0),
    make("pro-magic", "standing-block-end", 0),
    make("pro-magic", "standing-block-idle", 0),
    make("pro-magic", "standing-block-react-large", 0),
    make("pro-magic", "standing-block-start", 0),
    make("pro-magic", "standing-idle-02", 0),
    make("pro-magic", "standing-idle-03", 0),
    make("pro-magic", "standing-idle-04", 0),
    make("pro-magic", "standing-idle-to-crouch", 0),
    make("pro-magic", "standing-idle", 0),
    make("pro-magic", "standing-jump-running-landing", 0),
    make("pro-magic", "standing-jump-running", 0),
    make("pro-magic", "standing-jump", 0),
    make("pro-magic", "standing-land-to-standing-idle", 0),
    make("pro-magic", "standing-react-death-backward", 0),
    make("pro-magic", "standing-react-death-forward", 0),
    make("pro-magic", "standing-react-death-left", 0),
    make("pro-magic", "standing-react-death-right", 0),
    make("pro-magic", "standing-react-large-from-back", 0),
    make("pro-magic", "standing-react-large-from-front", 0),
    make("pro-magic", "standing-react-large-from-left", 0),
    make("pro-magic", "standing-react-large-from-right", 0),
    make("pro-magic", "standing-react-small-from-back", 0),
    make("pro-magic", "standing-react-small-from-front", 0),
    make("pro-magic", "standing-react-small-from-left", 0),
    make("pro-magic", "standing-react-small-from-right", 0),
    make("pro-magic", "standing-run-back", 0),
    make("pro-magic", "standing-run-forward", 0),
    make("pro-magic", "standing-run-left", 0),
    make("pro-magic", "standing-run-right", 0),
    make("pro-magic", "standing-sprint-forward", 0),
    make("pro-magic", "standing-turn-left-90", 0),
    make("pro-magic", "standing-turn-right-90", 0),
    make("pro-magic", "standing-walk-back", 0),
    make("pro-magic", "standing-walk-forward", 0),
    make("pro-magic", "standing-walk-left", 0),
    make("pro-magic", "standing-walk-right", 0),
  ] },
  { folder: "breakdance", title: "Breakdance", items: [
    make("breakdance", "breakdance-1990-2", 0),
    make("breakdance", "breakdance-1990-3", 0),
    make("breakdance", "breakdance-1990", 0),
    make("breakdance", "breakdance-ending-1", 0),
    make("breakdance", "breakdance-ending-2", 0),
    make("breakdance", "breakdance-ending-3", 0),
    make("breakdance", "breakdance-footwork-1", 0),
    make("breakdance", "breakdance-footwork-2", 0),
    make("breakdance", "breakdance-footwork-3", 0),
    make("breakdance", "breakdance-footwork-to-freeze", 0),
    make("breakdance", "breakdance-footwork-to-idle-2", 0),
    make("breakdance", "breakdance-footwork-to-idle", 0),
    make("breakdance", "breakdance-freeze-var-1", 0),
    make("breakdance", "breakdance-freeze-var-2", 0),
    make("breakdance", "breakdance-freeze-var-3", 0),
    make("breakdance", "breakdance-freeze-var-4", 0),
    make("breakdance", "breakdance-freezes", 0),
    make("breakdance", "breakdance-ready-2", 0),
    make("breakdance", "breakdance-ready-3", 0),
    make("breakdance", "breakdance-ready", 0),
    make("breakdance", "breakdance-swipes", 0),
    make("breakdance", "breakdance-uprock-2", 0),
    make("breakdance", "breakdance-uprock-to-ground-2", 0),
    make("breakdance", "breakdance-uprock-to-ground", 0),
    make("breakdance", "breakdance-uprock-var-1-end", 0),
    make("breakdance", "breakdance-uprock-var-1-start", 0),
    make("breakdance", "breakdance-uprock-var-1", 0),
    make("breakdance", "breakdance-uprock-var-2", 0),
    make("breakdance", "breakdance-uprock", 0),
    make("breakdance", "brooklyn-uprock", 0),
    make("breakdance", "crossleg-freeze", 0),
    make("breakdance", "flair-2", 0),
    make("breakdance", "flair-3", 0),
    make("breakdance", "flair", 0),
  ] },
  { folder: "gesture", title: "Gesture", items: [
    make("gesture", "acknowledging", 0.14),
    make("gesture", "angry-gesture", 0.14),
    make("gesture", "annoyed-head-shake", 0.14),
    make("gesture", "being-cocky", 0.14),
    make("gesture", "dismissing-gesture", 0.14),
    make("gesture", "happy-hand-gesture", 0.14),
    make("gesture", "hard-head-nod", 0.14),
    make("gesture", "head-nod-yes", 0.14),
    make("gesture", "lengthy-head-nod", 0.14),
    make("gesture", "look-away-gesture", 0.14),
    make("gesture", "relieved-sigh", 0.14),
    make("gesture", "sarcastic-head-nod", 0.14),
    make("gesture", "shaking-head-no", 0.14),
    make("gesture", "thoughtful-head-shake", 0.14),
    make("gesture", "weight-shift", 0.14),
  ] },
  { folder: "gun", title: "Gun", items: [
    make("gun", "crouching-turn-90-left", 0),
    make("gun", "crouching-turn-90-right", 0),
    make("gun", "death-crouching-headshot-front", 0),
    make("gun", "death-from-back-headshot", 0),
    make("gun", "death-from-front-headshot", 0),
    make("gun", "death-from-right", 0),
    make("gun", "death-from-the-back", 0),
    make("gun", "death-from-the-front", 0),
    make("gun", "idle-aiming", 0),
    make("gun", "idle-crouching-aiming", 0),
    make("gun", "idle-crouching", 0),
    make("gun", "idle", 0),
    make("gun", "jump-down", 0),
    make("gun", "jump-loop", 0),
    make("gun", "jump-up", 0),
    make("gun", "run-backward-left", 0),
    make("gun", "run-backward-right", 0),
    make("gun", "run-backward", 0),
    make("gun", "run-forward-left", 0),
    make("gun", "run-forward-right", 0),
    make("gun", "run-forward", 0),
    make("gun", "run-left", 0),
    make("gun", "run-right", 0),
    make("gun", "sprint-backward-left", 0),
    make("gun", "sprint-backward-right", 0),
    make("gun", "sprint-backward", 0),
    make("gun", "sprint-forward-left", 0),
    make("gun", "sprint-forward-right", 0),
    make("gun", "sprint-forward", 0),
    make("gun", "sprint-left", 0),
    make("gun", "sprint-right", 0),
    make("gun", "turn-90-left", 0),
    make("gun", "turn-90-right", 0),
    make("gun", "walk-backward-left", 0),
    make("gun", "walk-backward-right", 0),
    make("gun", "walk-backward", 0),
    make("gun", "walk-crouching-backward-left", 0),
    make("gun", "walk-crouching-backward-right", 0),
    make("gun", "walk-crouching-backward", 0),
    make("gun", "walk-crouching-forward-left", 0),
    make("gun", "walk-crouching-forward-right", 0),
    make("gun", "walk-crouching-forward", 0),
    make("gun", "walk-crouching-left", 0),
    make("gun", "walk-crouching-right", 0),
    make("gun", "walk-forward-left", 0),
    make("gun", "walk-forward-right", 0),
    make("gun", "walk-forward", 0),
    make("gun", "walk-left", 0),
    make("gun", "walk-right", 0),
  ] },
  { folder: "longbow", title: "Longbow", items: [
    make("longbow", "fall-a-land-to-run-forward", 0),
    make("longbow", "fall-a-land-to-standing-idle-01", 0),
    make("longbow", "fall-a-loop", 0),
    make("longbow", "standing-aim-overdraw", 0),
    make("longbow", "standing-aim-recoil", 0),
    make("longbow", "standing-aim-walk-back", 0),
    make("longbow", "standing-aim-walk-forward", 0),
    make("longbow", "standing-aim-walk-left", 0),
    make("longbow", "standing-aim-walk-right", 0),
    make("longbow", "standing-block", 0),
    make("longbow", "standing-death-backward-01", 0),
    make("longbow", "standing-death-forward-01", 0),
    make("longbow", "standing-disarm-bow", 0),
    make("longbow", "standing-dive-forward", 0),
    make("longbow", "standing-dodge-backward", 0),
    make("longbow", "standing-dodge-forward", 0),
    make("longbow", "standing-dodge-left", 0),
    make("longbow", "standing-dodge-right", 0),
    make("longbow", "standing-draw-arrow", 0),
    make("longbow", "standing-equip-bow", 0),
    make("longbow", "standing-idle-01", 0),
    make("longbow", "standing-idle-02-looking", 0),
    make("longbow", "standing-idle-03-examine", 0),
    make("longbow", "standing-melee-kick", 0),
    make("longbow", "standing-melee-punch", 0),
    make("longbow", "standing-react-small-from-front", 0),
    make("longbow", "standing-react-small-from-headshot", 0),
    make("longbow", "standing-run-back", 0),
    make("longbow", "standing-run-forward-stop", 0),
    make("longbow", "standing-run-forward", 0),
    make("longbow", "standing-run-left", 0),
    make("longbow", "standing-run-right", 0),
    make("longbow", "standing-turn-90-left", 0),
    make("longbow", "standing-turn-90-right", 0),
    make("longbow", "standing-walk-back", 0),
    make("longbow", "standing-walk-forward", 0),
    make("longbow", "standing-walk-left", 0),
    make("longbow", "standing-walk-right", 0),
    make("longbow", "unarmed-idle-01", 0),
  ] },
  { folder: "shooter", title: "Shooter", items: [
    make("shooter", "firing-rifle", 0),
    make("shooter", "jump-backward", 0),
    make("shooter", "jump-forward", 0),
    make("shooter", "rifle-aiming-idle", 0),
    make("shooter", "rifle-run", 0),
    make("shooter", "run-backwards", 0),
    make("shooter", "start-walking-backwards", 0),
    make("shooter", "start-walking", 0),
    make("shooter", "stop-walking", 0),
    make("shooter", "strafe-2", 0),
    make("shooter", "strafe", 0),
    make("shooter", "walk-backwards-stop", 0),
    make("shooter", "walking-backwards", 0),
    make("shooter", "walking-to-dying", 0),
    make("shooter", "walking", 0),
  ] },
];

/** Flat list of every playable emotion. */
export const EMOTION_FLAT: EmotionDef[] = EMOTION_GROUPS.flatMap((g) => g.items);
